use_frameworks!

target 'LYNetworking_Example' do
  pod 'LYNetworking', :path => '../'

  target 'LYNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
